[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ber-automation"
version = "0.1.0"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
include = ["ber_automation*"]
